version: 0.2
phases:
  build:
    commands:
      - echo Build started 
      - echo Compiling the Python code…..
      - unzip python.zip
  post_build: 
    commands:
      - echo Build completed 
      - pwd
      - ls -al
  
artifacts:
  files:
  - '**/*'
